Document: dwm
Title: Debian dwm Manual
Author: <insert document author here>
Abstract: This manual describes what dwm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dwm/dwm.sgml.gz

Format: postscript
Files: /usr/share/doc/dwm/dwm.ps.gz

Format: text
Files: /usr/share/doc/dwm/dwm.text.gz

Format: HTML
Index: /usr/share/doc/dwm/html/index.html
Files: /usr/share/doc/dwm/html/*.html
